stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    alias: docker
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

Docker Build:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk add --no-cache py-pip python3-dev libffi-dev openssl-dev gcc libc-dev docker-compose
    - rm -rf $HOME/.cache/pip /tmp/pip-build-*
    - pip install --upgrade setuptools pip
    - docker-compose build
    - docker tag $CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  tags:
    - docker

Django Tests:
  stage: test
  image: python:latest
  services:
    - name: docker:dind
  script:
    - rm -rf $HOME/.cache/pip /tmp/pip-build-*
    - pip install -r app/requirements.txt
    - docker-compose up -d
    - docker-compose exec web python manage.py migrate
    - docker-compose exec web python -m pytest
    - docker-compose down
  tags:
    - docker
  dependencies:
    - Docker Build

Release:
  stage: release
  image: docker:stable
  services:
    - name: docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest
  tags:
    - docker
  dependencies:
    - Django Tests
