image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache python3-dev libffi-dev gcc musl-dev
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip

build:
  stage: build
  tags:
    - docker
    - python
  script:
    - docker-compose -f docker-compose.yml build -t $CI_REGISTRY_IMAGE
    - docker-compose -f docker-compose.yml exec web python manage.py migrate

test:
  stage: test
  tags:
    - docker
    - python
  script:
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up --abort-on-container-exit
    - docker-compose -f docker-compose.yml exec web python -m pytest
  after_script:
    - docker-compose -f docker-compose.yml down

deploy:
  stage: deploy
  tags:
    - docker
    - python
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD https://gitlab.com/me7000428/bike-rent-tz
    - docker tag bike-rent-tz %CI_REGISTRY_IMAGE
    - docker push %CI_REGISTRY_IMAGE
