stages:
  - prepare
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose

prepare:
  stage: prepare
  script:
    - docker-compose up -d
    - docker-compose exec web python manage.py migrate
  tags:
    - docker

test:
  stage: test
  script:
    - docker-compose run web pytest
    - docker-compose down
  tags:
    - docker

build:
  stage: build
  script:
    - docker-compose build
  artifacts:
    paths:
      - docker-compose.yml
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
    # Здесь можно добавить команды для развертывания на вашем сервере
    - docker-compose up -d
    - docker-compose down
  tags:
    - docker
