# .gitlab-ci.yml

# Используем Docker executor
image: docker:stable

services:
  - docker:dind # сервис для доступа к Docker-демону внутри CI

stages:
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/ # адрес демона Docker, обслуживающего сервис docker:dind
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

pytest:
  stage: test
  script:
    - docker-compose up -d # запускаем тестовую среду с помощью Docker Compose
    - docker-compose exec web python manage.py migrate --noinput # проводим миграции в тестовой базе данных
    - docker-compose exec web pytest # запускаем тесты с pytest
    - docker-compose down # останавливаем тестовую среду после выполнения тестов
  services:
    - docker:19.03.12-dind # указываем версию сервиса docker:dind
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker-compose up -d # развертываем приложение с помощью Docker Compose
    - docker-compose down # останавливаем приложение после его развертывания
  services:
    - docker:19.03.12-dind # указываем версию сервиса docker:dind
  tags:
    - docker
