stages:
  - prepare
  - test
  - build
  - cleanup
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    alias: docker
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

before_script:
  - apk add --no-cache docker-compose

before_script:
  - docker info

prepare:
  stage: prepare
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml exec web python manage.py migrate

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml run web pytest

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
  artifacts:
    paths:
      - docker-compose.yml

cleanup:
  stage: cleanup
  script:
    - docker-compose -f docker-compose.yml down

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
    # Добавьте здесь команды для развертывания на вашем сервере
    - docker-compose -f docker-compose.yml up -d
  only:
    - master
